version: '3.9'

networks:
  app:
    driver: bridge

services:
  client:
    environment:
      - REGISTRY_USERNAME=${REGISTRY_USERNAME}
      - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
    image: ${IMAGE}
    ports:
      - '4000:4000'
    networks:
      - app

  # redis:
  #   container_name: redis
  #   restart: always
  #   image: redis:5.0.14
  #   command: redis-server /etc/redis/redis.conf
  #   networks:
  #     - app
  #   volumes:
  #     - /opt/docker/redis/conf/redis.conf:/etc/redis/redis.conf
  #     - /opt/docker/redis/data:/data
  #   ports:
  #     - "6379:6379"

  # mysql:
  #   image: mariadb:10.9
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./deploy/mariadb/conf:/etc/mysql
  #     - /data/docker/mysql/data:/var/lib/mysql
  #     - /data/docker/mysql/log:/var/log/mysql
  #   restart: always
  #   command:
  #     [
  #       '--character-set-server=utf8mb4',
  #       '--collation-server=utf8mb4_unicode_ci',
  #       '--lower_case_table_names=1',
  #       '--default-time-zone=+8:00',
  #     ]
  #   environment:
  #     MARIADB_DATABASE: nestjs_learning
  #     MARIADB_USER: nestjs_learning
  #     MARIADB_PASSWORD: nestjs_learning
  #     MARIADB_ROOT_PASSWORD: nestjs_learning2023
  #   networks:
  #     - app

  # adminer:
  #   image: adminer:latest
  #   restart: always
  #   ports:
  #     - 18080:8080
  #   networks:
  #     - app
